# Notebook: Instalación y Operaciones Básicas en NumPy

## Sección 1: Instalación y verificación

In [43]:
# (Este paso se realiza en consola, no en el notebook)

# pip install numpy
# conda install numpy

Verificar instalación desde Python:

In [44]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 1.26.4



## 🧩 Sección 2: Creación de Arrays

### 🔹 1. Array desde una lista

In [45]:
array1 = np.array([1, 2, 3, 4, 5])
print("Array desde lista:", array1)

Array desde lista: [1 2 3 4 5]


### 🔹 3. Array de unos

In [46]:
ones_array = np.ones(5)
print("Array de unos:", ones_array)

Array de unos: [1. 1. 1. 1. 1.]


### 🔹 4. Secuencia de valores

In [47]:
sequence_array = np.arange(0, 10, 2)
print("Array de secuencia:", sequence_array)

Array de secuencia: [0 2 4 6 8]


### 🔹 5. Array bidimensional

In [48]:
matrix_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz 2D:", matrix_2d)

Matriz 2D: [[1 2 3]
 [4 5 6]]


In [49]:
print ("Dimensiones de la matriz 2D:", matrix_2d.ndim)
print ("Forma de la matriz 2D:", matrix_2d.shape)
print ("Tamaño de la matriz 2D:", matrix_2d.size)

Dimensiones de la matriz 2D: 2
Forma de la matriz 2D: (2, 3)
Tamaño de la matriz 2D: 6


In [50]:
np.eye=np.eye(3)
print("Matriz identidad 3x3:", np.eye)
print("Matriz identidad 3x3 con np.eye:", np.eye(3))

TypeError: 'numpy.ndarray' object is not callable

## 🧩 Sección 3: Operaciones Básicas con Arrays

### 🔹 1. Suma y multiplicación

In [ ]:
a=array1
print (a)

In [ ]:
b = np.array([5, 6, 7, 8, 9])
suma = array1 + b
producto = array1 * b
print("Suma de arrays:", suma)
print("Producto elemento a elemento:", producto)

Suma de arrays: [ 6  8 10 12 14]
Producto elemento a elemento: [ 5 12 21 32 45]


In [ ]:
producto.sum
print ("Suma de todos los elementos del producto:", producto.sum())

Suma de todos los elementos del producto: 115



### 🔹 2. Funciones matemáticas

In [ ]:
raiz = np.sqrt(array1)
seno = np.sin(array1)
exponencial = np.exp(array1)
print("Raíz cuadrada:", raiz)
print("Seno:", seno)
print("Exponencial:", exponencial)

Raíz cuadrada: [1.         1.41421356 1.73205081 2.         2.23606798]
Seno: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Exponencial: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]



### 🔹 3. Estadísticas básicas

In [ ]:
print("Media:", np.mean(array1))
print("Máximo:", np.max(array1))
print("Mínimo:", np.min(array1))

Media: 3.0
Máximo: 5
Mínimo: 1


## 🧩 Sección 4: Manipulación de Arrays

### 🔹 1. Cambio de forma (reshape)


In [ ]:
reshaped_array = np.arange(6).reshape(3, 2)
print("Array reestructurado:", reshaped_array)

### 🔹 2. Transposición

In [ ]:
print("Transpuesto:", reshaped_array.T)

### 🔹 3. Concatenación

In [ ]:
concat_array = np.concatenate([array1, b])
print("Concatenación:", concat_array)

### 🔹 4. División de arrays

In [ ]:
split_array = np.split(array1, 5)
print("División:", split_array)

## 🧪 Sección 5: Ejercicios Extra para Clase

### ✏️ Ejercicio 1:
> Crear un array de 15 elementos y reestructurarlo en una matriz de 5 filas y 3 columnas.



In [ ]:
array = np.arange(1, 16)  

matriz = array.reshape(5, 3)

print(matriz)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


### ✏️ Ejercicio 2:
> Crear una matriz identidad de 4x4.




In [6]:
import numpy as np

Matriz = np.eye(4)
print("Matriz identidad 4x4:", Matriz)


Matriz identidad 4x4: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### ✏️ Ejercicio 3:
> Generar un array de 10 valores linealmente espaciados entre 0 y 5.



In [7]:
import numpy as np
array = np.linspace (0, 5, 10)
print(array)


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### ✏️ Ejercicio 4:
> Concatenar dos arrays 1D y dividir el resultado en tres partes iguales.



In [8]:
import numpy as np

array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

array_concatenado = np.concatenate((array1, array2))
print("Array concatenado:", array_concatenado)


arrays_divididos = np.array_split(array_concatenado, 3)
print("Arrays divididos:")
for parte in arrays_divididos:
    print(parte)

Array concatenado: [1 2 3 4 5 6 7 8]
Arrays divididos:
[1 2 3]
[4 5 6]
[7 8]


### ✏️ Ejercicio 5:
> Crear un array de 10 números aleatorios entre 0 y 1. Calcular su media y desviación estándar.



In [9]:
import numpy as np
array_aleatorio= np.random.rand(10)
print("Array aleatorio:", array_aleatorio)

media= np.mean(array_aleatorio)
print("Media del array aleatorio:", media)

desviacio_estandar= np.std(array_aleatorio)
print("Desviación estándar del array aleatorio:", desviacio_estandar)



Array aleatorio: [0.17618874 0.31293301 0.79498485 0.74867658 0.54618518 0.2611481
 0.86701194 0.61204975 0.40767812 0.35708825]
Media del array aleatorio: 0.5083944518012382
Desviación estándar del array aleatorio: 0.22877555132579508


### 🔥 Ejercicio 6 (Desafío):
> Crear una función que reciba un array y devuelva otro array normalizado entre 0 y 1 (es decir, valores entre el mínimo y máximo del array).

In [10]:
import numpy as np

def normalizar_array(arr):
    min_val = np.min(arr)
    max_val = np.max(arr)
    return (arr - min_val) / (max_val - min_val)

array = np.array([5, 15, 25, 35, 45])
array_normalizado = normalizar_array(array)
print("Array normalizado:", array_normalizado)

Array normalizado: [0.   0.25 0.5  0.75 1.  ]
